### PR TITLE
Discovering kernel driver for block devices on SLE12

### PR DESCRIPTION
**Pull request by mjura**
For SLE12 there is problem with dicovering virtio block_devices.
We would like to parse and new attribute kernel driver for block device.
This will be easy way to check if disk is virtio.

    if node[:block_device]["vda"]["driver"] == "virtio_blk"
      ...
    end

### CODE REVIEW

**Comment by tboerger** [comment]
:+1: but gating fails.

**Comment by mjura** [comment]
> :+1: but gating fails.

Thank you! Yes, gating tests wonder me, I tried rebuild them, I think that was some general issue with mkcloud.

**Comment by dirkmueller** [comment]
after milestone 2..

**Comment by rsalevsky** [comment]
@mjura, this repository got merged into [crowbar-core](https://github.com/crowbar/crowbar-core).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by mjura** [comment]
This change will be not needed, I've implement solution in barclamp-provisioner

**Pull request closed without merging**
