### PR TITLE
backport of bnc#945219 workaround

### PR DESCRIPTION
**Pull request by rhafer**
This backport the recent additions and fixes of the OvsBridge class. It's required by the real fix in the neutron barclamp.

### CODE REVIEW

**Comment by rhafer** [comment]
Please to not merged yet as it is largely untested.

**Comment by rhafer** [comment]
I've reworked this now to be a complete backport of the changes we did for master, instead of just partially backporting it. The minimize approach that I tried first didn't really work out.

**Comment by rhafer** [comment]
As this PR doesn't have any real dependencies on the other PRs related to the openvswitch rework I think this one is ready for merge now.

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
